### ISSUE TITLE
Nothing happens on Nexus 5X (Android 6.0, API 23)

### ISSUE THREAD

**Issue by exrhizo** [googlesamples/android-HdrViewfinder#2]
Nothing seems to happen visually, it doesn't display the permission request and nothing seems to happen at all, just showing the phone home screen, as though the app isn't running at all.

However logcat shows that it get past posting the permissions request.

Last thing it says is:

```
 08-12 22:23:29.459 25946-26017/com.example.android.hdrviewfinder D/OpenGLRenderer: Use     EGL_SWAP_BEHAVIOR_PRESERVED: true

      [ 08-12 22:23:29.467 25946:25946 D/         ]
      HostConnection::get() New Host Connection established 0xaa99ece0, tid 25946

      [ 08-12 22:23:29.520 25946:26017 D/         ]
      HostConnection::get() New Host Connection established 0xae407630, tid 26017
```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
