### ISSUE TITLE
asus zenfone 3 z012da not working

### ISSUE THREAD

**Issue by lilgcheng** [googlesamples/android-HdrViewfinder#3]
-06 22:26:50.207 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: Event ID not found
06-06 22:26:50.227 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: AK Error: 
06-06 22:26:50.227 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: Event ID not found
06-06 22:26:50.257 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: AK Error: 
06-06 22:26:50.257 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: Event ID not found
06-06 22:26:50.277 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: AK Error: 
06-06 22:26:50.277 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: Event ID not found
06-06 22:26:50.297 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: AK Error: 
06-06 22:26:50.297 2908-3015/com.nexon.dynastywarriors I/AKDEBUG: Event ID not found

android Monitor display

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
