### ISSUE TITLE
Camera preview is upside down on NEXUS 5X running Android 7.1.2

### ISSUE THREAD

**Issue by vladcipariu91** [googlesamples/android-HdrViewfinder#4]
![device-2017-08-14-135555](https://user-images.githubusercontent.com/12483168/29272520-55f5b538-80f8-11e7-955a-301f431b13c3.png)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
