### ISSUE TITLE
No back-facing sufficiently capable camera available!

### ISSUE THREAD

**Issue by ammaratef45** [googlesamples/android-HdrViewfinder#5]
I tried the app on more than one device (All have front and back cameras)
I always get the message

> No back-facing sufficiently capable camera available!

With debugging I found that `(hasFullLevel || hasEnoughCapability)` always false.

Is that a problem with my devices?! What feature should be there so that the example can run on my device?

**Comment by alexcohn** [comment]
Yes, this device cannot do HDR. You need a device with more advanced back camera.

**Comment by ammaratef45** [comment]
@alexcohn thanks
