### ISSUE TITLE
Why not also in portrait mode ?

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-HdrViewfinder#6]
hello, 
I found that project great, but could you provide also an example which shows this in portrait mode ? I mean that the camera preview is rotated to the left when the screenOrientation attribute in the manifest is set to  portrait. A user might also use the app only in portrait mode. Since there is no other project available which combines a RenderScript and Camera2 with regard to image/video processing, I would be thankful if you could provide a solution for that. At StackOverflow I posted a question for this lack of portrait mode option (see https://stackoverflow.com/questions/57794282/rotating-yuv-image-data-for-portrait-mode-using-renderscript) and I posted my solution. But that was not very successful as you will see from the question.

Such an adjustment to your code would be great. 

Thanks in advance :)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
